// Code generated by goctl. DO NOT EDIT.
package types

type IndexVO struct {
	Message string `json:"message"`
}

type StartDto struct {
	JobType string `json:"jobType"`
	JobSpec string `json:"jobSpec"`
}

type StartResp struct {
	Code    int         `json:"code"`
	Message string      `json:"messsage"`
	Data    interface{} `json:"data"`
}
