// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: Storage.proto

package server

import (
	"context"

	"Storage/internal/logic/generateservice"
	"Storage/internal/svc"
	"Storage/storage"
)

type GenerateServiceServer struct {
	svcCtx *svc.ServiceContext
	storage.UnimplementedGenerateServiceServer
}

func NewGenerateServiceServer(svcCtx *svc.ServiceContext) *GenerateServiceServer {
	return &GenerateServiceServer{
		svcCtx: svcCtx,
	}
}

// 根据ApiInfo生成依赖、提取器、预期
func (s *GenerateServiceServer) GenerateDependency(ctx context.Context, in *storage.GenerateDependencyRequest) (*storage.GenerateDependencyResponse, error) {
	l := generateservicelogic.NewGenerateDependencyLogic(ctx, s.svcCtx)
	return l.GenerateDependency(in)
}

func (s *GenerateServiceServer) GenerateExtractor(ctx context.Context, in *storage.GenerateExtractorRequest) (*storage.GenerateExtractorResponse, error) {
	l := generateservicelogic.NewGenerateExtractorLogic(ctx, s.svcCtx)
	return l.GenerateExtractor(in)
}

func (s *GenerateServiceServer) GenerateExpect(ctx context.Context, in *storage.GenerateExpectRequest) (*storage.GenerateExpectResponse, error) {
	l := generateservicelogic.NewGenerateExpectLogic(ctx, s.svcCtx)
	return l.GenerateExpect(in)
}
