// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: Storage.proto

package server

import (
	"context"

	"Storage/internal/logic/reportservice"
	"Storage/internal/svc"
	"Storage/storage"
)

type ReportServiceServer struct {
	svcCtx *svc.ServiceContext
	storage.UnimplementedReportServiceServer
}

func NewReportServiceServer(svcCtx *svc.ServiceContext) *ReportServiceServer {
	return &ReportServiceServer{
		svcCtx: svcCtx,
	}
}

// 测试报告
func (s *ReportServiceServer) GetReport(ctx context.Context, in *storage.GetTestReportRequest) (*storage.TestReportResponse, error) {
	l := reportservicelogic.NewGetReportLogic(ctx, s.svcCtx)
	return l.GetReport(in)
}

func (s *ReportServiceServer) ListReports(ctx context.Context, in *storage.GetTaskReportListRequest) (*storage.ReportListResponse, error) {
	l := reportservicelogic.NewListReportsLogic(ctx, s.svcCtx)
	return l.ListReports(in)
}

func (s *ReportServiceServer) DeleteReport(ctx context.Context, in *storage.GetTestReportRequest) (*storage.DeleteResponse, error) {
	l := reportservicelogic.NewDeleteReportLogic(ctx, s.svcCtx)
	return l.DeleteReport(in)
}
