// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: Storage.proto

package sceneconfigservice

import (
	"context"

	"Storage/storage"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApifoxConfig               = storage.ApifoxConfig
	CreateSceneConfigRequest   = storage.CreateSceneConfigRequest
	CreateTaskRequest          = storage.CreateTaskRequest
	CreateTestDataRequest      = storage.CreateTestDataRequest
	DeleteInterfaceRequest     = storage.DeleteInterfaceRequest
	DeleteResponse             = storage.DeleteResponse
	DeleteSceneConfigRequest   = storage.DeleteSceneConfigRequest
	DeleteTaskRequest          = storage.DeleteTaskRequest
	DeleteTestDataRequest      = storage.DeleteTestDataRequest
	Dependency                 = storage.Dependency
	Empty                      = storage.Empty
	ExecuteTaskRequest         = storage.ExecuteTaskRequest
	ExecuteTaskResponse        = storage.ExecuteTaskResponse
	Expect                     = storage.Expect
	ExtractConfig              = storage.ExtractConfig
	Extractor                  = storage.Extractor
	GenerateDependencyRequest  = storage.GenerateDependencyRequest
	GenerateDependencyResponse = storage.GenerateDependencyResponse
	GenerateExpectRequest      = storage.GenerateExpectRequest
	GenerateExpectResponse     = storage.GenerateExpectResponse
	GenerateExtractorRequest   = storage.GenerateExtractorRequest
	GenerateExtractorResponse  = storage.GenerateExtractorResponse
	GetInterfaceListResponse   = storage.GetInterfaceListResponse
	GetInterfaceRequest        = storage.GetInterfaceRequest
	GetInterfaceResponse       = storage.GetInterfaceResponse
	GetSceneConfigRequest      = storage.GetSceneConfigRequest
	GetTaskReportListRequest   = storage.GetTaskReportListRequest
	GetTaskRequest             = storage.GetTaskRequest
	GetTestDataRequest         = storage.GetTestDataRequest
	GetTestReportRequest       = storage.GetTestReportRequest
	Header                     = storage.Header
	InterfaceInfo              = storage.InterfaceInfo
	ListSceneConfigsRequest    = storage.ListSceneConfigsRequest
	ListValue                  = storage.ListValue
	MongoConfig                = storage.MongoConfig
	Parameter                  = storage.Parameter
	RelatedApi                 = storage.RelatedApi
	ReportListResponse         = storage.ReportListResponse
	ResponseHeader             = storage.ResponseHeader
	RetrySetting               = storage.RetrySetting
	Scenarios                  = storage.Scenarios
	SceneConfig                = storage.SceneConfig
	SceneConfigListResponse    = storage.SceneConfigListResponse
	SceneConfigResponse        = storage.SceneConfigResponse
	Strategy                   = storage.Strategy
	Struct                     = storage.Struct
	SyncDestination            = storage.SyncDestination
	SyncInterfaceRequest       = storage.SyncInterfaceRequest
	SyncInterfaceResponse      = storage.SyncInterfaceResponse
	SyncSource                 = storage.SyncSource
	Task                       = storage.Task
	TaskAPISpec                = storage.TaskAPISpec
	TaskListResponse           = storage.TaskListResponse
	TaskListResponse_TaskItem  = storage.TaskListResponse_TaskItem
	TaskMeta                   = storage.TaskMeta
	TaskResponse               = storage.TaskResponse
	TaskSyncSpec               = storage.TaskSyncSpec
	TestData                   = storage.TestData
	TestDataListResponse       = storage.TestDataListResponse
	TestDataResponse           = storage.TestDataResponse
	TestReport                 = storage.TestReport
	TestReportResponse         = storage.TestReportResponse
	TimeoutSetting             = storage.TimeoutSetting
	Timestamp                  = storage.Timestamp
	UpdateSceneConfigRequest   = storage.UpdateSceneConfigRequest
	UpdateTaskRequest          = storage.UpdateTaskRequest
	UpdateTestDataRequest      = storage.UpdateTestDataRequest
	Value                      = storage.Value

	SceneConfigService interface {
		// 场景配置
		CreateSceneConfig(ctx context.Context, in *CreateSceneConfigRequest, opts ...grpc.CallOption) (*SceneConfigResponse, error)
		GetSceneConfig(ctx context.Context, in *GetSceneConfigRequest, opts ...grpc.CallOption) (*SceneConfigResponse, error)
		UpdateSceneConfig(ctx context.Context, in *UpdateSceneConfigRequest, opts ...grpc.CallOption) (*SceneConfigResponse, error)
		DeleteSceneConfig(ctx context.Context, in *DeleteSceneConfigRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
		ListSceneConfigs(ctx context.Context, in *ListSceneConfigsRequest, opts ...grpc.CallOption) (*SceneConfigListResponse, error)
	}

	defaultSceneConfigService struct {
		cli zrpc.Client
	}
)

func NewSceneConfigService(cli zrpc.Client) SceneConfigService {
	return &defaultSceneConfigService{
		cli: cli,
	}
}

// 场景配置
func (m *defaultSceneConfigService) CreateSceneConfig(ctx context.Context, in *CreateSceneConfigRequest, opts ...grpc.CallOption) (*SceneConfigResponse, error) {
	client := storage.NewSceneConfigServiceClient(m.cli.Conn())
	return client.CreateSceneConfig(ctx, in, opts...)
}

func (m *defaultSceneConfigService) GetSceneConfig(ctx context.Context, in *GetSceneConfigRequest, opts ...grpc.CallOption) (*SceneConfigResponse, error) {
	client := storage.NewSceneConfigServiceClient(m.cli.Conn())
	return client.GetSceneConfig(ctx, in, opts...)
}

func (m *defaultSceneConfigService) UpdateSceneConfig(ctx context.Context, in *UpdateSceneConfigRequest, opts ...grpc.CallOption) (*SceneConfigResponse, error) {
	client := storage.NewSceneConfigServiceClient(m.cli.Conn())
	return client.UpdateSceneConfig(ctx, in, opts...)
}

func (m *defaultSceneConfigService) DeleteSceneConfig(ctx context.Context, in *DeleteSceneConfigRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	client := storage.NewSceneConfigServiceClient(m.cli.Conn())
	return client.DeleteSceneConfig(ctx, in, opts...)
}

func (m *defaultSceneConfigService) ListSceneConfigs(ctx context.Context, in *ListSceneConfigsRequest, opts ...grpc.CallOption) (*SceneConfigListResponse, error) {
	client := storage.NewSceneConfigServiceClient(m.cli.Conn())
	return client.ListSceneConfigs(ctx, in, opts...)
}
