// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: Storage.proto

package server

import (
	"context"

	"Storage/internal/logic/taskconfigservice"
	"Storage/internal/svc"
	"Storage/storage"
)

type TaskConfigServiceServer struct {
	svcCtx *svc.ServiceContext
	storage.UnimplementedTaskConfigServiceServer
}

func NewTaskConfigServiceServer(svcCtx *svc.ServiceContext) *TaskConfigServiceServer {
	return &TaskConfigServiceServer{
		svcCtx: svcCtx,
	}
}

// 任务管理
func (s *TaskConfigServiceServer) CreateTask(ctx context.Context, in *storage.CreateTaskRequest) (*storage.TaskResponse, error) {
	l := taskconfigservicelogic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

func (s *TaskConfigServiceServer) GetTask(ctx context.Context, in *storage.GetTaskRequest) (*storage.TaskResponse, error) {
	l := taskconfigservicelogic.NewGetTaskLogic(ctx, s.svcCtx)
	return l.GetTask(in)
}

func (s *TaskConfigServiceServer) UpdateTask(ctx context.Context, in *storage.UpdateTaskRequest) (*storage.TaskResponse, error) {
	l := taskconfigservicelogic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

func (s *TaskConfigServiceServer) DeleteTask(ctx context.Context, in *storage.DeleteTaskRequest) (*storage.DeleteResponse, error) {
	l := taskconfigservicelogic.NewDeleteTaskLogic(ctx, s.svcCtx)
	return l.DeleteTask(in)
}

func (s *TaskConfigServiceServer) ListTasks(ctx context.Context, in *storage.Empty) (*storage.TaskListResponse, error) {
	l := taskconfigservicelogic.NewListTasksLogic(ctx, s.svcCtx)
	return l.ListTasks(in)
}
