// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: Storage.proto

package server

import (
	"context"

	"Storage/internal/logic/executeservice"
	"Storage/internal/svc"
	"Storage/storage"
)

type ExecuteServiceServer struct {
	svcCtx *svc.ServiceContext
	storage.UnimplementedExecuteServiceServer
}

func NewExecuteServiceServer(svcCtx *svc.ServiceContext) *ExecuteServiceServer {
	return &ExecuteServiceServer{
		svcCtx: svcCtx,
	}
}

// 任务执行
func (s *ExecuteServiceServer) ExecuteTask(ctx context.Context, in *storage.ExecuteTaskRequest) (*storage.ExecuteTaskResponse, error) {
	l := executeservicelogic.NewExecuteTaskLogic(ctx, s.svcCtx)
	return l.ExecuteTask(in)
}
