// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: Storage.proto

package server

import (
	"context"

	"Storage/internal/logic/testdataservice"
	"Storage/internal/svc"
	"Storage/storage"
)

type TestDataServiceServer struct {
	svcCtx *svc.ServiceContext
	storage.UnimplementedTestDataServiceServer
}

func NewTestDataServiceServer(svcCtx *svc.ServiceContext) *TestDataServiceServer {
	return &TestDataServiceServer{
		svcCtx: svcCtx,
	}
}

// 测试数据
func (s *TestDataServiceServer) CreateTestData(ctx context.Context, in *storage.CreateTestDataRequest) (*storage.TestDataResponse, error) {
	l := testdataservicelogic.NewCreateTestDataLogic(ctx, s.svcCtx)
	return l.CreateTestData(in)
}

func (s *TestDataServiceServer) GetTestData(ctx context.Context, in *storage.GetTestDataRequest) (*storage.TestDataResponse, error) {
	l := testdataservicelogic.NewGetTestDataLogic(ctx, s.svcCtx)
	return l.GetTestData(in)
}

func (s *TestDataServiceServer) UpdateTestData(ctx context.Context, in *storage.UpdateTestDataRequest) (*storage.TestDataResponse, error) {
	l := testdataservicelogic.NewUpdateTestDataLogic(ctx, s.svcCtx)
	return l.UpdateTestData(in)
}

func (s *TestDataServiceServer) DeleteTestData(ctx context.Context, in *storage.DeleteTestDataRequest) (*storage.DeleteResponse, error) {
	l := testdataservicelogic.NewDeleteTestDataLogic(ctx, s.svcCtx)
	return l.DeleteTestData(in)
}

func (s *TestDataServiceServer) ListTestData(ctx context.Context, in *storage.Empty) (*storage.TestDataListResponse, error) {
	l := testdataservicelogic.NewListTestDataLogic(ctx, s.svcCtx)
	return l.ListTestData(in)
}
